### ISSUE TITLE
Chrome Webstore Link to Wrong Place

### ISSUE THREAD

**Issue by kevin51jiang** [KnlnKS/lever-parser-extension#2]
Hello!

Currently the link to the "developer's support site" goes to `https://github.com/KnlnKS/lever-parser-extension/issueshttps://github.com/KnlnKS/lever-parser-extension/issues`.

Just an FYI if you want to fix that

![image](https://user-images.githubusercontent.com/33907581/127763662-1f674932-9349-4b35-8f39-8112b5366f17.png)

**Comment by KnlnKS** [comment]
I must have hit `ctrl-v` twice. The link should be fixed in v0.3.
